// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/user.proto

package org.nutz.plugins.protobuf.pojo;

public final class UserProto {
	private UserProto() {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface UserOrBuilder extends com.google.protobuf.MessageOrBuilder {

		// optional int64 id = 1;
		/**
		 * <code>optional int64 id = 1;</code>
		 */
		boolean hasId();

		/**
		 * <code>optional int64 id = 1;</code>
		 */
		long getId();

		// optional string name = 2;
		/**
		 * <code>optional string name = 2;</code>
		 */
		boolean hasName();

		/**
		 * <code>optional string name = 2;</code>
		 */
		java.lang.String getName();

		/**
		 * <code>optional string name = 2;</code>
		 */
		com.google.protobuf.ByteString getNameBytes();

		// repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;
		/**
		 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
		 */
		java.util.List<org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber> getPhoneList();

		/**
		 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
		 */
		org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber getPhone(int index);

		/**
		 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
		 */
		int getPhoneCount();

		/**
		 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
		 */
		java.util.List<? extends org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumberOrBuilder> getPhoneOrBuilderList();

		/**
		 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
		 */
		org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumberOrBuilder getPhoneOrBuilder(int index);
	}

	/**
	 * Protobuf type {@code com.rekoe.protobuf.pojo.User}
	 */
	public static final class User extends com.google.protobuf.GeneratedMessage implements UserOrBuilder {
		// Use User.newBuilder() to construct.
		private User(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
			super(builder);
			this.unknownFields = builder.getUnknownFields();
		}

		private User(boolean noInit) {
			this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
		}

		private static final User defaultInstance;

		public static User getDefaultInstance() {
			return defaultInstance;
		}

		public User getDefaultInstanceForType() {
			return defaultInstance;
		}

		private final com.google.protobuf.UnknownFieldSet unknownFields;

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private User(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 8: {
						bitField0_ |= 0x00000001;
						id_ = input.readInt64();
						break;
					}
					case 18: {
						bitField0_ |= 0x00000002;
						name_ = input.readBytes();
						break;
					}
					case 34: {
						if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
							phone_ = new java.util.ArrayList<org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber>();
							mutable_bitField0_ |= 0x00000004;
						}
						phone_.add(input.readMessage(org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber.PARSER, extensionRegistry));
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
			} finally {
				if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
					phone_ = java.util.Collections.unmodifiableList(phone_);
				}
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return org.nutz.plugins.protobuf.pojo.UserProto.internal_static_com_rekoe_protobuf_pojo_User_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return org.nutz.plugins.protobuf.pojo.UserProto.internal_static_com_rekoe_protobuf_pojo_User_fieldAccessorTable.ensureFieldAccessorsInitialized(org.nutz.plugins.protobuf.pojo.UserProto.User.class, org.nutz.plugins.protobuf.pojo.UserProto.User.Builder.class);
		}

		public static com.google.protobuf.Parser<User> PARSER = new com.google.protobuf.AbstractParser<User>() {
			public User parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
				return new User(input, extensionRegistry);
			}
		};

		@java.lang.Override
		public com.google.protobuf.Parser<User> getParserForType() {
			return PARSER;
		}

		public interface PhoneNumberOrBuilder extends com.google.protobuf.MessageOrBuilder {

			// required string number = 1;
			/**
			 * <code>required string number = 1;</code>
			 */
			boolean hasNumber();

			/**
			 * <code>required string number = 1;</code>
			 */
			java.lang.String getNumber();

			/**
			 * <code>required string number = 1;</code>
			 */
			com.google.protobuf.ByteString getNumberBytes();
		}

		/**
		 * Protobuf type {@code com.rekoe.protobuf.pojo.User.PhoneNumber}
		 */
		public static final class PhoneNumber extends com.google.protobuf.GeneratedMessage implements PhoneNumberOrBuilder {
			// Use PhoneNumber.newBuilder() to construct.
			private PhoneNumber(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
				super(builder);
				this.unknownFields = builder.getUnknownFields();
			}

			private PhoneNumber(boolean noInit) {
				this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
			}

			private static final PhoneNumber defaultInstance;

			public static PhoneNumber getDefaultInstance() {
				return defaultInstance;
			}

			public PhoneNumber getDefaultInstanceForType() {
				return defaultInstance;
			}

			private final com.google.protobuf.UnknownFieldSet unknownFields;

			@java.lang.Override
			public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
				return this.unknownFields;
			}

			private PhoneNumber(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
				initFields();
				com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
				try {
					boolean done = false;
					while (!done) {
						int tag = input.readTag();
						switch (tag) {
						case 0:
							done = true;
							break;
						default: {
							if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
								done = true;
							}
							break;
						}
						case 10: {
							bitField0_ |= 0x00000001;
							number_ = input.readBytes();
							break;
						}
						}
					}
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.setUnfinishedMessage(this);
				} catch (java.io.IOException e) {
					throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
				} finally {
					this.unknownFields = unknownFields.build();
					makeExtensionsImmutable();
				}
			}

			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return org.nutz.plugins.protobuf.pojo.UserProto.internal_static_com_rekoe_protobuf_pojo_User_PhoneNumber_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return org.nutz.plugins.protobuf.pojo.UserProto.internal_static_com_rekoe_protobuf_pojo_User_PhoneNumber_fieldAccessorTable.ensureFieldAccessorsInitialized(org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber.class, org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber.Builder.class);
			}

			public static com.google.protobuf.Parser<PhoneNumber> PARSER = new com.google.protobuf.AbstractParser<PhoneNumber>() {
				public PhoneNumber parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
					return new PhoneNumber(input, extensionRegistry);
				}
			};

			@java.lang.Override
			public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
				return PARSER;
			}

			private int bitField0_;
			// required string number = 1;
			public static final int NUMBER_FIELD_NUMBER = 1;
			private java.lang.Object number_;

			/**
			 * <code>required string number = 1;</code>
			 */
			public boolean hasNumber() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>required string number = 1;</code>
			 */
			public java.lang.String getNumber() {
				java.lang.Object ref = number_;
				if (ref instanceof java.lang.String) {
					return (java.lang.String) ref;
				} else {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					java.lang.String s = bs.toStringUtf8();
					if (bs.isValidUtf8()) {
						number_ = s;
					}
					return s;
				}
			}

			/**
			 * <code>required string number = 1;</code>
			 */
			public com.google.protobuf.ByteString getNumberBytes() {
				java.lang.Object ref = number_;
				if (ref instanceof java.lang.String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
					number_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			private void initFields() {
				number_ = "";
			}

			private byte memoizedIsInitialized = -1;

			public final boolean isInitialized() {
				byte isInitialized = memoizedIsInitialized;
				if (isInitialized != -1)
					return isInitialized == 1;

				if (!hasNumber()) {
					memoizedIsInitialized = 0;
					return false;
				}
				memoizedIsInitialized = 1;
				return true;
			}

			public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
				getSerializedSize();
				if (((bitField0_ & 0x00000001) == 0x00000001)) {
					output.writeBytes(1, getNumberBytes());
				}
				getUnknownFields().writeTo(output);
			}

			private int memoizedSerializedSize = -1;

			public int getSerializedSize() {
				int size = memoizedSerializedSize;
				if (size != -1)
					return size;

				size = 0;
				if (((bitField0_ & 0x00000001) == 0x00000001)) {
					size += com.google.protobuf.CodedOutputStream.computeBytesSize(1, getNumberBytes());
				}
				size += getUnknownFields().getSerializedSize();
				memoizedSerializedSize = size;
				return size;
			}

			private static final long serialVersionUID = 0L;

			@java.lang.Override
			protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
				return super.writeReplace();
			}

			public static org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data);
			}

			public static org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data, extensionRegistry);
			}

			public static org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data);
			}

			public static org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
				return PARSER.parseFrom(data, extensionRegistry);
			}

			public static org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber parseFrom(java.io.InputStream input) throws java.io.IOException {
				return PARSER.parseFrom(input);
			}

			public static org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				return PARSER.parseFrom(input, extensionRegistry);
			}

			public static org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
				return PARSER.parseDelimitedFrom(input);
			}

			public static org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				return PARSER.parseDelimitedFrom(input, extensionRegistry);
			}

			public static org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
				return PARSER.parseFrom(input);
			}

			public static org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				return PARSER.parseFrom(input, extensionRegistry);
			}

			public static Builder newBuilder() {
				return Builder.create();
			}

			public Builder newBuilderForType() {
				return newBuilder();
			}

			public static Builder newBuilder(org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber prototype) {
				return newBuilder().mergeFrom(prototype);
			}

			public Builder toBuilder() {
				return newBuilder(this);
			}

			@java.lang.Override
			protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				Builder builder = new Builder(parent);
				return builder;
			}

			/**
			 * Protobuf type {@code com.rekoe.protobuf.pojo.User.PhoneNumber}
			 */
			public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumberOrBuilder {
				public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
					return org.nutz.plugins.protobuf.pojo.UserProto.internal_static_com_rekoe_protobuf_pojo_User_PhoneNumber_descriptor;
				}

				protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
					return org.nutz.plugins.protobuf.pojo.UserProto.internal_static_com_rekoe_protobuf_pojo_User_PhoneNumber_fieldAccessorTable.ensureFieldAccessorsInitialized(org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber.class, org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber.Builder.class);
				}

				// Construct using
				// com.rekoe.protobuf.pojo.UserProto.User.PhoneNumber.newBuilder()
				private Builder() {
					maybeForceBuilderInitialization();
				}

				private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
					super(parent);
					maybeForceBuilderInitialization();
				}

				private void maybeForceBuilderInitialization() {
					if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					}
				}

				private static Builder create() {
					return new Builder();
				}

				public Builder clear() {
					super.clear();
					number_ = "";
					bitField0_ = (bitField0_ & ~0x00000001);
					return this;
				}

				public Builder clone() {
					return create().mergeFrom(buildPartial());
				}

				public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
					return org.nutz.plugins.protobuf.pojo.UserProto.internal_static_com_rekoe_protobuf_pojo_User_PhoneNumber_descriptor;
				}

				public org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber getDefaultInstanceForType() {
					return org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber.getDefaultInstance();
				}

				public org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber build() {
					org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber result = buildPartial();
					if (!result.isInitialized()) {
						throw newUninitializedMessageException(result);
					}
					return result;
				}

				public org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber buildPartial() {
					org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber result = new org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber(this);
					int from_bitField0_ = bitField0_;
					int to_bitField0_ = 0;
					if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
						to_bitField0_ |= 0x00000001;
					}
					result.number_ = number_;
					result.bitField0_ = to_bitField0_;
					onBuilt();
					return result;
				}

				public Builder mergeFrom(com.google.protobuf.Message other) {
					if (other instanceof org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber) {
						return mergeFrom((org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber) other);
					} else {
						super.mergeFrom(other);
						return this;
					}
				}

				public Builder mergeFrom(org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber other) {
					if (other == org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber.getDefaultInstance())
						return this;
					if (other.hasNumber()) {
						bitField0_ |= 0x00000001;
						number_ = other.number_;
						onChanged();
					}
					this.mergeUnknownFields(other.getUnknownFields());
					return this;
				}

				public final boolean isInitialized() {
					if (!hasNumber()) {

						return false;
					}
					return true;
				}

				public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
					org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber parsedMessage = null;
					try {
						parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
					} catch (com.google.protobuf.InvalidProtocolBufferException e) {
						parsedMessage = (org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber) e.getUnfinishedMessage();
						throw e;
					} finally {
						if (parsedMessage != null) {
							mergeFrom(parsedMessage);
						}
					}
					return this;
				}

				private int bitField0_;

				// required string number = 1;
				private java.lang.Object number_ = "";

				/**
				 * <code>required string number = 1;</code>
				 */
				public boolean hasNumber() {
					return ((bitField0_ & 0x00000001) == 0x00000001);
				}

				/**
				 * <code>required string number = 1;</code>
				 */
				public java.lang.String getNumber() {
					java.lang.Object ref = number_;
					if (!(ref instanceof java.lang.String)) {
						java.lang.String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
						number_ = s;
						return s;
					} else {
						return (java.lang.String) ref;
					}
				}

				/**
				 * <code>required string number = 1;</code>
				 */
				public com.google.protobuf.ByteString getNumberBytes() {
					java.lang.Object ref = number_;
					if (ref instanceof String) {
						com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
						number_ = b;
						return b;
					} else {
						return (com.google.protobuf.ByteString) ref;
					}
				}

				/**
				 * <code>required string number = 1;</code>
				 */
				public Builder setNumber(java.lang.String value) {
					if (value == null) {
						throw new NullPointerException();
					}
					bitField0_ |= 0x00000001;
					number_ = value;
					onChanged();
					return this;
				}

				/**
				 * <code>required string number = 1;</code>
				 */
				public Builder clearNumber() {
					bitField0_ = (bitField0_ & ~0x00000001);
					number_ = getDefaultInstance().getNumber();
					onChanged();
					return this;
				}

				/**
				 * <code>required string number = 1;</code>
				 */
				public Builder setNumberBytes(com.google.protobuf.ByteString value) {
					if (value == null) {
						throw new NullPointerException();
					}
					bitField0_ |= 0x00000001;
					number_ = value;
					onChanged();
					return this;
				}

				// @@protoc_insertion_point(builder_scope:com.rekoe.protobuf.pojo.User.PhoneNumber)
			}

			static {
				defaultInstance = new PhoneNumber(true);
				defaultInstance.initFields();
			}

			// @@protoc_insertion_point(class_scope:com.rekoe.protobuf.pojo.User.PhoneNumber)
		}

		private int bitField0_;
		// optional int64 id = 1;
		public static final int ID_FIELD_NUMBER = 1;
		private long id_;

		/**
		 * <code>optional int64 id = 1;</code>
		 */
		public boolean hasId() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>optional int64 id = 1;</code>
		 */
		public long getId() {
			return id_;
		}

		// optional string name = 2;
		public static final int NAME_FIELD_NUMBER = 2;
		private java.lang.Object name_;

		/**
		 * <code>optional string name = 2;</code>
		 */
		public boolean hasName() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		/**
		 * <code>optional string name = 2;</code>
		 */
		public java.lang.String getName() {
			java.lang.Object ref = name_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					name_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>optional string name = 2;</code>
		 */
		public com.google.protobuf.ByteString getNameBytes() {
			java.lang.Object ref = name_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				name_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;
		public static final int PHONE_FIELD_NUMBER = 4;
		private java.util.List<org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber> phone_;

		/**
		 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
		 */
		public java.util.List<org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber> getPhoneList() {
			return phone_;
		}

		/**
		 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
		 */
		public java.util.List<? extends org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumberOrBuilder> getPhoneOrBuilderList() {
			return phone_;
		}

		/**
		 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
		 */
		public int getPhoneCount() {
			return phone_.size();
		}

		/**
		 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
		 */
		public org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber getPhone(int index) {
			return phone_.get(index);
		}

		/**
		 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
		 */
		public org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumberOrBuilder getPhoneOrBuilder(int index) {
			return phone_.get(index);
		}

		private void initFields() {
			id_ = 0L;
			name_ = "";
			phone_ = java.util.Collections.emptyList();
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			for (int i = 0; i < getPhoneCount(); i++) {
				if (!getPhone(i).isInitialized()) {
					memoizedIsInitialized = 0;
					return false;
				}
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt64(1, id_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(2, getNameBytes());
			}
			for (int i = 0; i < phone_.size(); i++) {
				output.writeMessage(4, phone_.get(i));
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt64Size(1, id_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(2, getNameBytes());
			}
			for (int i = 0; i < phone_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(4, phone_.get(i));
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static org.nutz.plugins.protobuf.pojo.UserProto.User parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static org.nutz.plugins.protobuf.pojo.UserProto.User parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static org.nutz.plugins.protobuf.pojo.UserProto.User parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static org.nutz.plugins.protobuf.pojo.UserProto.User parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static org.nutz.plugins.protobuf.pojo.UserProto.User parseFrom(java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static org.nutz.plugins.protobuf.pojo.UserProto.User parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static org.nutz.plugins.protobuf.pojo.UserProto.User parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static org.nutz.plugins.protobuf.pojo.UserProto.User parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}

		public static org.nutz.plugins.protobuf.pojo.UserProto.User parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static org.nutz.plugins.protobuf.pojo.UserProto.User parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(org.nutz.plugins.protobuf.pojo.UserProto.User prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code com.rekoe.protobuf.pojo.User}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements org.nutz.plugins.protobuf.pojo.UserProto.UserOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return org.nutz.plugins.protobuf.pojo.UserProto.internal_static_com_rekoe_protobuf_pojo_User_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return org.nutz.plugins.protobuf.pojo.UserProto.internal_static_com_rekoe_protobuf_pojo_User_fieldAccessorTable.ensureFieldAccessorsInitialized(org.nutz.plugins.protobuf.pojo.UserProto.User.class, org.nutz.plugins.protobuf.pojo.UserProto.User.Builder.class);
			}

			// Construct using
			// com.rekoe.protobuf.pojo.UserProto.User.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getPhoneFieldBuilder();
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				id_ = 0L;
				bitField0_ = (bitField0_ & ~0x00000001);
				name_ = "";
				bitField0_ = (bitField0_ & ~0x00000002);
				if (phoneBuilder_ == null) {
					phone_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000004);
				} else {
					phoneBuilder_.clear();
				}
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return org.nutz.plugins.protobuf.pojo.UserProto.internal_static_com_rekoe_protobuf_pojo_User_descriptor;
			}

			public org.nutz.plugins.protobuf.pojo.UserProto.User getDefaultInstanceForType() {
				return org.nutz.plugins.protobuf.pojo.UserProto.User.getDefaultInstance();
			}

			public org.nutz.plugins.protobuf.pojo.UserProto.User build() {
				org.nutz.plugins.protobuf.pojo.UserProto.User result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public org.nutz.plugins.protobuf.pojo.UserProto.User buildPartial() {
				org.nutz.plugins.protobuf.pojo.UserProto.User result = new org.nutz.plugins.protobuf.pojo.UserProto.User(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.id_ = id_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.name_ = name_;
				if (phoneBuilder_ == null) {
					if (((bitField0_ & 0x00000004) == 0x00000004)) {
						phone_ = java.util.Collections.unmodifiableList(phone_);
						bitField0_ = (bitField0_ & ~0x00000004);
					}
					result.phone_ = phone_;
				} else {
					result.phone_ = phoneBuilder_.build();
				}
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof org.nutz.plugins.protobuf.pojo.UserProto.User) {
					return mergeFrom((org.nutz.plugins.protobuf.pojo.UserProto.User) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(org.nutz.plugins.protobuf.pojo.UserProto.User other) {
				if (other == org.nutz.plugins.protobuf.pojo.UserProto.User.getDefaultInstance())
					return this;
				if (other.hasId()) {
					setId(other.getId());
				}
				if (other.hasName()) {
					bitField0_ |= 0x00000002;
					name_ = other.name_;
					onChanged();
				}
				if (phoneBuilder_ == null) {
					if (!other.phone_.isEmpty()) {
						if (phone_.isEmpty()) {
							phone_ = other.phone_;
							bitField0_ = (bitField0_ & ~0x00000004);
						} else {
							ensurePhoneIsMutable();
							phone_.addAll(other.phone_);
						}
						onChanged();
					}
				} else {
					if (!other.phone_.isEmpty()) {
						if (phoneBuilder_.isEmpty()) {
							phoneBuilder_.dispose();
							phoneBuilder_ = null;
							phone_ = other.phone_;
							bitField0_ = (bitField0_ & ~0x00000004);
							phoneBuilder_ = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ? getPhoneFieldBuilder() : null;
						} else {
							phoneBuilder_.addAllMessages(other.phone_);
						}
					}
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				for (int i = 0; i < getPhoneCount(); i++) {
					if (!getPhone(i).isInitialized()) {

						return false;
					}
				}
				return true;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				org.nutz.plugins.protobuf.pojo.UserProto.User parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (org.nutz.plugins.protobuf.pojo.UserProto.User) e.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			// optional int64 id = 1;
			private long id_;

			/**
			 * <code>optional int64 id = 1;</code>
			 */
			public boolean hasId() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>optional int64 id = 1;</code>
			 */
			public long getId() {
				return id_;
			}

			/**
			 * <code>optional int64 id = 1;</code>
			 */
			public Builder setId(long value) {
				bitField0_ |= 0x00000001;
				id_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional int64 id = 1;</code>
			 */
			public Builder clearId() {
				bitField0_ = (bitField0_ & ~0x00000001);
				id_ = 0L;
				onChanged();
				return this;
			}

			// optional string name = 2;
			private java.lang.Object name_ = "";

			/**
			 * <code>optional string name = 2;</code>
			 */
			public boolean hasName() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			/**
			 * <code>optional string name = 2;</code>
			 */
			public java.lang.String getName() {
				java.lang.Object ref = name_;
				if (!(ref instanceof java.lang.String)) {
					java.lang.String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					name_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>optional string name = 2;</code>
			 */
			public com.google.protobuf.ByteString getNameBytes() {
				java.lang.Object ref = name_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
					name_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>optional string name = 2;</code>
			 */
			public Builder setName(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				name_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional string name = 2;</code>
			 */
			public Builder clearName() {
				bitField0_ = (bitField0_ & ~0x00000002);
				name_ = getDefaultInstance().getName();
				onChanged();
				return this;
			}

			/**
			 * <code>optional string name = 2;</code>
			 */
			public Builder setNameBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				name_ = value;
				onChanged();
				return this;
			}

			// repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;
			private java.util.List<org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber> phone_ = java.util.Collections.emptyList();

			private void ensurePhoneIsMutable() {
				if (!((bitField0_ & 0x00000004) == 0x00000004)) {
					phone_ = new java.util.ArrayList<org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber>(phone_);
					bitField0_ |= 0x00000004;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilder<org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber, org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber.Builder, org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumberOrBuilder> phoneBuilder_;

			/**
			 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
			 */
			public java.util.List<org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber> getPhoneList() {
				if (phoneBuilder_ == null) {
					return java.util.Collections.unmodifiableList(phone_);
				} else {
					return phoneBuilder_.getMessageList();
				}
			}

			/**
			 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
			 */
			public int getPhoneCount() {
				if (phoneBuilder_ == null) {
					return phone_.size();
				} else {
					return phoneBuilder_.getCount();
				}
			}

			/**
			 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
			 */
			public org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber getPhone(int index) {
				if (phoneBuilder_ == null) {
					return phone_.get(index);
				} else {
					return phoneBuilder_.getMessage(index);
				}
			}

			/**
			 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
			 */
			public Builder setPhone(int index, org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber value) {
				if (phoneBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensurePhoneIsMutable();
					phone_.set(index, value);
					onChanged();
				} else {
					phoneBuilder_.setMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
			 */
			public Builder setPhone(int index, org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber.Builder builderForValue) {
				if (phoneBuilder_ == null) {
					ensurePhoneIsMutable();
					phone_.set(index, builderForValue.build());
					onChanged();
				} else {
					phoneBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
			 */
			public Builder addPhone(org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber value) {
				if (phoneBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensurePhoneIsMutable();
					phone_.add(value);
					onChanged();
				} else {
					phoneBuilder_.addMessage(value);
				}
				return this;
			}

			/**
			 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
			 */
			public Builder addPhone(int index, org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber value) {
				if (phoneBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensurePhoneIsMutable();
					phone_.add(index, value);
					onChanged();
				} else {
					phoneBuilder_.addMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
			 */
			public Builder addPhone(org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber.Builder builderForValue) {
				if (phoneBuilder_ == null) {
					ensurePhoneIsMutable();
					phone_.add(builderForValue.build());
					onChanged();
				} else {
					phoneBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
			 */
			public Builder addPhone(int index, org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber.Builder builderForValue) {
				if (phoneBuilder_ == null) {
					ensurePhoneIsMutable();
					phone_.add(index, builderForValue.build());
					onChanged();
				} else {
					phoneBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
			 */
			public Builder addAllPhone(java.lang.Iterable<? extends org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber> values) {
				if (phoneBuilder_ == null) {
					ensurePhoneIsMutable();
					super.addAll(values, phone_);
					onChanged();
				} else {
					phoneBuilder_.addAllMessages(values);
				}
				return this;
			}

			/**
			 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
			 */
			public Builder clearPhone() {
				if (phoneBuilder_ == null) {
					phone_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000004);
					onChanged();
				} else {
					phoneBuilder_.clear();
				}
				return this;
			}

			/**
			 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
			 */
			public Builder removePhone(int index) {
				if (phoneBuilder_ == null) {
					ensurePhoneIsMutable();
					phone_.remove(index);
					onChanged();
				} else {
					phoneBuilder_.remove(index);
				}
				return this;
			}

			/**
			 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
			 */
			public org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber.Builder getPhoneBuilder(int index) {
				return getPhoneFieldBuilder().getBuilder(index);
			}

			/**
			 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
			 */
			public org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumberOrBuilder getPhoneOrBuilder(int index) {
				if (phoneBuilder_ == null) {
					return phone_.get(index);
				} else {
					return phoneBuilder_.getMessageOrBuilder(index);
				}
			}

			/**
			 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
			 */
			public java.util.List<? extends org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumberOrBuilder> getPhoneOrBuilderList() {
				if (phoneBuilder_ != null) {
					return phoneBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(phone_);
				}
			}

			/**
			 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
			 */
			public org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber.Builder addPhoneBuilder() {
				return getPhoneFieldBuilder().addBuilder(org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber.getDefaultInstance());
			}

			/**
			 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
			 */
			public org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber.Builder addPhoneBuilder(int index) {
				return getPhoneFieldBuilder().addBuilder(index, org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber.getDefaultInstance());
			}

			/**
			 * <code>repeated .com.rekoe.protobuf.pojo.User.PhoneNumber phone = 4;</code>
			 */
			public java.util.List<org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber.Builder> getPhoneBuilderList() {
				return getPhoneFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilder<org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber, org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber.Builder, org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumberOrBuilder> getPhoneFieldBuilder() {
				if (phoneBuilder_ == null) {
					phoneBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber, org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumber.Builder, org.nutz.plugins.protobuf.pojo.UserProto.User.PhoneNumberOrBuilder>(phone_, ((bitField0_ & 0x00000004) == 0x00000004), getParentForChildren(), isClean());
					phone_ = null;
				}
				return phoneBuilder_;
			}

			// @@protoc_insertion_point(builder_scope:com.rekoe.protobuf.pojo.User)
		}

		static {
			defaultInstance = new User(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:com.rekoe.protobuf.pojo.User)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_com_rekoe_protobuf_pojo_User_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_com_rekoe_protobuf_pojo_User_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_com_rekoe_protobuf_pojo_User_PhoneNumber_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_com_rekoe_protobuf_pojo_User_PhoneNumber_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\020proto/user.proto\022\027com.rekoe.protobuf.p" + "ojo\"y\n\004User\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\0228\n" + "\005phone\030\004 \003(\0132).com.rekoe.protobuf.pojo.U" + "ser.PhoneNumber\032\035\n\013PhoneNumber\022\016\n\006number" + "\030\001 \002(\tB$\n\027com.rekoe.protobuf.pojoB\tUserP" + "roto" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_com_rekoe_protobuf_pojo_User_descriptor = getDescriptor().getMessageTypes().get(0);
				internal_static_com_rekoe_protobuf_pojo_User_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(internal_static_com_rekoe_protobuf_pojo_User_descriptor, new java.lang.String[] { "Id", "Name", "Phone", });
				internal_static_com_rekoe_protobuf_pojo_User_PhoneNumber_descriptor = internal_static_com_rekoe_protobuf_pojo_User_descriptor.getNestedTypes().get(0);
				internal_static_com_rekoe_protobuf_pojo_User_PhoneNumber_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(internal_static_com_rekoe_protobuf_pojo_User_PhoneNumber_descriptor, new java.lang.String[] { "Number", });
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
